### ISSUE TITLE
Better Response Handling

### ISSUE THREAD

**Issue by mglodack** [awseward/restivus#9]
Hello,

This is a pretty sweet .NET rest client. Haven't found one this nice. :+1: 

I would like to be able to add some hooks or be able to process the `HttpResponseMessage` myself.

Currently, if a bad request has happened it will throw an exception as demonstrated here. https://github.com/awseward/restivus/compare/master...mglodack:fails_before_deserializing

I noticed that the SendAsync method is calling [EnsureSuccessStatusCode()](https://msdn.microsoft.com/en-us/library/system.net.http.httpresponsemessage.ensuresuccessstatuscode%28v=vs.118%29.aspx) in the codebase [here](https://github.com/awseward/restivus/blob/master/src/Restivus/HttpRequestSender.cs#L75).

What do you thing about having the `SendAsync` method return `HttpResponseMessage` instead of type `T`?

**Comment by awseward** [comment]
So I believe the current implementation does have you handling the `HttpResponseMessage` when it comes back, but I think that the `EnsureStatusSuccessCode` is really the issue here, because it's preventing the callback from getting a change to handle the `HttpResponseMessage` at all...

Removing that `EnsureStatusSuccessCode` call might be all we need to do here...

**Comment by awseward** [comment]
This should be solved by https://github.com/awseward/restivus/pull/12.

Let me know if that is not the case.
